# Database settings
database:
  # PostgreSQL Database-URL
  # Format: postgresql://<user>:<password>@<host>/<database>
  # you can add optional postgres parameters after the database part, e.g. ?sslmode=verify-full
  url: "postgresql://<user>:<password>@<host>/<database>"

# Mastodon Instance settings
mastodon:
  # URL of your Mastodon Instance
  # Format: https://mastodon.social (without trailing slash)
  url: "https://"

  # Access token for your mastodon account
  # see $your_mastodon_url/settings/applications
  token: ""

  # Interval in which humble-bot tries to post bundles
  # format: "20s" or "15m" or "1h"
  # default: 5m
  postinterval: "5m"

  # Post visibility of the bundles on mastodon
  # allowed values: ["public", "unlisted", "private"]
  # default: public
  visibility: "public"

# Humble Bundle settings
humblebundle:

  # Interval in which humble-bot tries to query humblebundle.com
  # format: "20s" or "15m" or "1h"
  # default: 30m
  pollinterval: "30m"